### ISSUE TITLE
Buttons dont register finger movement.

### ISSUE THREAD

**Issue by meepingsnesroms** [pedja1/SMC-Android#10]
If you touch a button and move your finger off or slide your finger on it does not recognize that it was pressed or released.

**Comment by ramael** [comment]
I'm facing the same issue. The overlay controls are too picky: the do not active unless your finger is exactly over them.

**Comment by pedja1** [comment]
I will look into this. Thanks for reporting

**Comment by MrStahlfelge** [comment]
I suggest using [scene2d.ui Touchpad](https://github.com/libgdx/libgdx/wiki/Scene2d.ui#touchpad)

**Comment by MrStahlfelge** [comment]
Done in my fork

**Comment by MrStahlfelge** [comment]
Can be closed now
