### ISSUE TITLE
SMC v0.5alpha does not start

### ISSUE THREAD

**Issue by ramael** [pedja1/SMC-Android#12]
I've already tried to reinstall and clear cache and user date, but smc does not start.
Where can i find logs?

**Comment by pedja1** [comment]
Did you build app from source or install from Play Store?
If you built it from source, then you need to pack following folders in zip.
/data/data
/data/data_1080
/data/data_768
/data/data_540

Rename this file to "main.{versionCode}.rs.pedjaapps.smc.android.debug.obb" and put it in /sdcard/Android/obb/rs.pedjaapps.smc/android.debug folder on you android.

To pull the logs you can user "adb"

If you want to run it on desktop than you have to rename file to assets.zip and put it into android/assets folder in project

**Comment by ramael** [comment]
I installed it from the PlayStore after registering for the test section of the store.
I will try your suggestions.

**Comment by ramael** [comment]
Ok, solved: in Marshmallow you need to explicitly grant permission to storage (Settings -> App -> SMC Info -> Permissions)

**Comment by pedja1** [comment]
You are right, haven't really thought about  Marshmallow permissions
